from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('loginout/', views.logoutUser, name="logout"),

    path('', views.home, name="home"),
    path('cogreview/', views.cogreview, name="cogreview"),
    path('log/', views.log, name="log"),
    path('autoLog/', views.autoLog, name="autoLog"),
    path('view/', views.view, name="view"),
    path('update/<str:pk>/', views.update, name="update"),
    path('complete/<str:pk>/', views.complete, name="complete"),
    path('delete/<str:pk>/', views.delete, name="delete"),
    path('t2Prov/', views.t2Prov, name="t2Prov"),
    path('t2ProvGrabber/', views.t2ProvGrabber, name="t2ProvGrabber"),
    path('t2ProvCheck/<str:pk>', views.t2ProvCheck, name="t2ProvCheck"),
    path('t2ProvView/<str:pk>', views.t2ProvView, name="t2ProvView"),
    path('troubleTicket/', views.troubleTicket, name="troubleTicket"),
    path('changeOrder/', views.changeOrder, name="changeOrder"),
    path('ddt/', views.ddt, name="ddt"),
    path('troubleTicketGrabber/', views.troubleTicketGrabber, name="troubleTicketGrabber"),
    path('changeOrderGrabber/', views.changeOrderGrabber, name="changeOrderGrabber"),
    path('ddtGrabber/', views.ddtGrabber, name="ddtGrabber"),
    path('troubleTicketCheck/<str:pk>', views.troubleTicketCheck, name="troubleTicketCheck"),
    path('changeOrderCheck/<str:pk>', views.changeOrderCheck, name="changeOrderCheck"),
    path('ddtCheck/<str:pk>', views.ddtCheck, name="ddtCheck"),
    path('troubleTicketView/<str:pk>', views.troubleTicketView, name="troubleTicketView"),
    path('changeOrderView/<str:pk>', views.changeOrderView, name="changeOrderView"),
    path('ddtView/<str:pk>', views.ddtView, name="ddtView"),
    path('export/', views.export, name="export"),
    path('dailyWork/', views.dailyWork, name="dailyWork"),
    path('sendBackTroubleTicket/<str:pk>/', views.sendBackTroubleTicket, name="sendBackTroubleTicket"),
    path('sendBackChangeOrder/<str:pk>/', views.sendBackChangeOrder, name="sendBackChangeOrder"),
    path('sendBackDdt/<str:pk>/', views.sendBackDdt, name="sendBackDdt"),
    path('sendToBoss/<str:pk>/', views.sendToBoss, name="sendToBoss"),
    path('sendBackCollectionDisconnect/<str:pk>/', views.sendBackCollectionDisconnect, name="sendBackCollectionDisconnect"),
    path('collectionDisconnect/', views.collectionDisconnect, name="collectionDisconnect"),
    path('collectionDisconnectGrabber/', views.collectionDisconnectGrabber, name="collectionDisconnectGrabber"),
    path('collectionDisconnectCheck/<str:pk>/', views.collectionDisconnectCheck, name="collectionDisconnectCheck"),
    path('collectionDisconnectView/<str:pk>/', views.collectionDisconnectView, name="collectionDisconnectView"),
    path('dropdown/', views.dropdown, name="dropdown"),
    path('troubleTicketDropdown/', views.troubleTicketDropdown, name="troubleTicketDropdown"),
    path('changeOrderDropdown/', views.changeOrderDropdown, name="changeOrderDropdown"),
    path('ddtDropdown/', views.ddtDropdown, name="ddtDropdown"),
    path('collectionDisconnectDropdown/', views.collectionDisconnectDropdown, name="collectionDisconnectDropdown"),
    path('data/', views.data, name="data"),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), name="password_reset_complete"),
]