# Generated by Django 3.1.1 on 2021-01-13 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productivity', models.CharField(max_length=200, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ddt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, null=True)),
                ('CID', models.CharField(max_length=200, null=True)),
                ('SUB_Start', models.CharField(max_length=200, null=True)),
                ('SUB_Stop', models.CharField(max_length=200, null=True)),
                ('amdocs_Plus', models.CharField(max_length=200, null=True)),
                ('serial', models.CharField(max_length=200, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('completion_Status', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Duplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MDU_ID', models.CharField(max_length=200, null=True)),
                ('PROPERTYNAME', models.CharField(max_length=200, null=True)),
                ('CUST_ACCT', models.CharField(max_length=200, null=True)),
                ('SITE_ID', models.CharField(max_length=200, null=True)),
                ('CUSTOMERNAME', models.CharField(max_length=200, null=True)),
                ('FULLADDRESS', models.CharField(max_length=200, null=True)),
                ('ONTSERIAL', models.CharField(max_length=200, null=True)),
                ('OFFERNUM', models.CharField(max_length=200, null=True)),
                ('ORDERNUMBER', models.CharField(max_length=200, null=True)),
                ('ORDERDATE', models.CharField(max_length=200, null=True)),
                ('CUSTOMEREFFECTIVEDATE', models.CharField(max_length=200, null=True)),
                ('BILLINGEFFECTIVEDATE', models.CharField(max_length=200, null=True)),
                ('ORDERTYPE', models.CharField(max_length=200, null=True)),
                ('COMPLETE', models.CharField(max_length=200, null=True)),
                ('ORDERSTATUS', models.CharField(max_length=200, null=True)),
                ('OLDSERVICE', models.CharField(max_length=200, null=True)),
                ('NEWSERVICE', models.CharField(max_length=200, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('completion_Status', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_Number', models.CharField(max_length=200, null=True)),
                ('cognito_Number', models.CharField(max_length=200, null=True)),
                ('employee', models.CharField(max_length=200, null=True)),
                ('site', models.CharField(max_length=200, null=True)),
                ('services', models.CharField(choices=[('Iptv', 'Iptv'), ('Voice', 'Voice'), ('Data', 'Data'), ('Analog', 'Analog'), ('Outage', 'Outage'), ('Miscellaneous', 'Miscellaneous'), ('All_Services', 'All_Services')], max_length=500, null=True)),
                ('source', models.CharField(choices=[('Install', 'Install'), ('Email Chain', 'Email Chain'), ('Fision Enterprise', 'Fision Enterprise'), ('Disco/Reco', 'Disco/Reco'), ('Project', 'Project'), ('Collections', 'Collections'), ('Miscellaneous', 'Miscellaneous'), ('Cog Call Back', 'Cog Call Back'), ('Inbound Tech Call', 'Inbound Tech Call'), ('Inbound Account Manager', 'Inbound Account Manager'), ('Inbound CS Agent', 'Inbound CS Agent'), ('Salisbury Gen tech support', 'Salisbury Gen tech support'), ('Fiber support', 'Fiber support'), ('change orders/disconnects/reconnects', 'change orders/disconnects/reconnects'), ('Trouble Ticket', 'Trouble Ticket'), ('Secure Plus', 'Secure Plus')], max_length=500, null=True)),
                ('troubleshoot_Required', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=500, null=True)),
                ('notes', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('Resolved With Dispatch', 'Resolved With Dispatch'), ('Resolved no dispatch', 'Resolved no dispatch'), ('Resolved-NTF', 'Resolved-NTF'), ('Pending Dispatch', 'Pending Dispatch'), ('Supervisor escalation', 'Supervisor escalation'), ('Jira escalation', 'Jira escalation'), ('Avoidable Escalation', 'Avoidable Escalation'), ('Miscellaneous', 'Miscellaneous'), ('Invalid VNN assigned', 'Invalid VNN assigned'), ('Number not assigned', 'Number not assigned'), ('Provisioning', 'Provisioning')], max_length=500, null=True)),
                ('resolution', models.CharField(max_length=500, null=True)),
                ('submission_Timer', models.CharField(max_length=200, null=True)),
                ('clock', models.CharField(max_length=200, null=True)),
                ('completion_Status', models.CharField(choices=[('Submitted', 'Submitted'), ('Reviewed', 'Reviewed'), ('Complete', 'Complete')], max_length=500, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MDU_ID', models.CharField(max_length=200, null=True)),
                ('MNAME', models.CharField(max_length=200, null=True)),
                ('CustomerNumber', models.CharField(max_length=200, null=True)),
                ('SITE_ID', models.CharField(max_length=200, null=True)),
                ('CustomerName', models.CharField(max_length=200, null=True)),
                ('FullAddress', models.CharField(max_length=200, null=True)),
                ('TicketNumber', models.CharField(max_length=200, null=True)),
                ('OPRID', models.CharField(max_length=200, null=True)),
                ('ContactEmployee', models.CharField(max_length=200, null=True)),
                ('TroubleCallReceived', models.CharField(max_length=200, null=True)),
                ('CallReason', models.CharField(max_length=200, null=True)),
                ('NoScheduleReason', models.CharField(max_length=200, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('completion_Status', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provisioning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MDU_ID', models.CharField(max_length=200, null=True)),
                ('PROPERTYNAME', models.CharField(max_length=200, null=True)),
                ('CUST_ACCT', models.CharField(max_length=200, null=True)),
                ('SITE_ID', models.CharField(max_length=200, null=True)),
                ('CUSTOMERNAME', models.CharField(max_length=200, null=True)),
                ('FULLADDRESS', models.CharField(max_length=200, null=True)),
                ('ONTSERIAL', models.CharField(max_length=200, null=True)),
                ('OFFERNUM', models.CharField(max_length=200, null=True)),
                ('ORDERNUMBER', models.CharField(max_length=200, null=True)),
                ('ORDERDATE', models.CharField(max_length=200, null=True)),
                ('CUSTOMEREFFECTIVEDATE', models.CharField(max_length=200, null=True)),
                ('BILLINGEFFECTIVEDATE', models.CharField(max_length=200, null=True)),
                ('ORDERTYPE', models.CharField(max_length=200, null=True)),
                ('COMPLETE', models.CharField(max_length=200, null=True)),
                ('ORDERSTATUS', models.CharField(max_length=200, null=True)),
                ('OLDSERVICE', models.CharField(max_length=200, null=True)),
                ('NEWSERVICE', models.CharField(max_length=200, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('completion_Status', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_Name', models.CharField(max_length=200, null=True)),
                ('number_of_Tickets_Completed_Today', models.CharField(max_length=200, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
