# Generated by Django 3.1.2 on 2020-11-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ddt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, null=True)),
                ('CID', models.CharField(max_length=200, null=True)),
                ('SUB_Start', models.CharField(max_length=200, null=True)),
                ('SUB_Stop', models.CharField(max_length=200, null=True)),
                ('amdocs_Plus', models.CharField(max_length=200, null=True)),
                ('serial', models.CharField(max_length=200, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
