# Generated by Django 3.1.2 on 2020-11-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ddt'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MDU_ID', models.CharField(max_length=200, null=True)),
                ('MNAME', models.CharField(max_length=200, null=True)),
                ('CustomerNumber', models.CharField(max_length=200, null=True)),
                ('SITE_ID', models.CharField(max_length=200, null=True)),
                ('CustomerName', models.CharField(max_length=200, null=True)),
                ('FullAddress', models.CharField(max_length=200, null=True)),
                ('TicketNumber', models.CharField(max_length=200, null=True)),
                ('OPRID', models.CharField(max_length=200, null=True)),
                ('ContactEmployee', models.CharField(max_length=200, null=True)),
                ('TroubleCallReceived', models.CharField(max_length=200, null=True)),
                ('CallReason', models.CharField(max_length=200, null=True)),
                ('NoScheduleReason', models.CharField(max_length=200, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
