# Generated by Django 3.1.2 on 2020-11-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_noschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provisioning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MDU_ID', models.CharField(max_length=200, null=True)),
                ('PROEPRTYNAME', models.CharField(max_length=200, null=True)),
                ('CUST_ACCT', models.CharField(max_length=200, null=True)),
                ('SITE_ID', models.CharField(max_length=200, null=True)),
                ('CUSTOMERNAME', models.CharField(max_length=200, null=True)),
                ('FULLADDRESS', models.CharField(max_length=200, null=True)),
                ('ONTSERIAL', models.CharField(max_length=200, null=True)),
                ('OFFERNUM', models.CharField(max_length=200, null=True)),
                ('ORDERNUMBER', models.CharField(max_length=200, null=True)),
                ('ORDERDATE', models.CharField(max_length=200, null=True)),
                ('CUSTOMEREFFECTIVEDATE', models.CharField(max_length=200, null=True)),
                ('BILLINGEFFECTIVEDATE', models.CharField(max_length=200, null=True)),
                ('ORDERTYPE', models.CharField(max_length=200, null=True)),
                ('COMPLETE', models.CharField(max_length=200, null=True)),
                ('ORDERSTATUS', models.CharField(max_length=200, null=True)),
                ('OLDSERVICE', models.CharField(max_length=200, null=True)),
                ('NEWSERVICE', models.CharField(max_length=200, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
