# Generated by Django 3.1.2 on 2020-12-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_provisioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='submission_Timer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
