# Generated by Django 3.1.2 on 2020-12-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_log_submission_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddt',
            name='completion_Status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noschedule',
            name='completion_Status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='provisioning',
            name='completion_Status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
