# Generated by Django 3.1.2 on 2020-12-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201222_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='source',
            field=models.CharField(choices=[('Install', 'Install'), ('No schedule Trouble', 'No schedule Trouble'), ('DDT Pending Provisioning', 'DDT Pending Provisioning'), ('Email Chain', 'Email Chain'), ('Fision Enterprise', 'Fision Enterprise'), ('Disco/Reco', 'Disco/Reco'), ('Project', 'Project'), ('Collections', 'Collections'), ('Miscellaneous', 'Miscellaneous'), ('Inbound Tech Call', 'Inbound Tech Call'), ('Inbound Account Manager', 'Inbound Account Manager'), ('Inbound CS Agent', 'Inbound CS Agent'), ('Salisbury Gen tech support', 'Salisbury Gen tech support'), ('Fiber support', 'Fiber support'), ('orders/disconnects/reconnects', 'orders/disconnects/reconnects')], max_length=500, null=True),
        ),
    ]
