# Generated by Django 3.1.2 on 2020-12-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201222_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provisioning',
            old_name='PROEPRTYNAME',
            new_name='PROPERTYNAME',
        ),
        migrations.AlterField(
            model_name='log',
            name='source',
            field=models.CharField(choices=[('Install', 'Install'), ('Email Chain', 'Email Chain'), ('Fision Enterprise', 'Fision Enterprise'), ('Disco/Reco', 'Disco/Reco'), ('Project', 'Project'), ('Collections', 'Collections'), ('Miscellaneous', 'Miscellaneous'), ('Inbound Tech Call', 'Inbound Tech Call'), ('Inbound Account Manager', 'Inbound Account Manager'), ('Inbound CS Agent', 'Inbound CS Agent'), ('Salisbury Gen tech support', 'Salisbury Gen tech support'), ('Fiber support', 'Fiber support'), ('change orders/disconnects/reconnects', 'change orders/disconnects/reconnects'), ('Trouble Ticket', 'Trouble Ticket'), ('DDT', 'DDT')], max_length=500, null=True),
        ),
    ]
