# Generated by Django 3.1.2 on 2021-01-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210113_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='dateReviewed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
