# Generated by Django 3.1.2 on 2021-01-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_log_datereviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionDisconnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.CharField(max_length=200, null=True)),
                ('OfferNumber', models.CharField(max_length=200, null=True)),
                ('ActionSuspendDowngrade', models.CharField(max_length=200, null=True)),
                ('PropertyName', models.CharField(max_length=200, null=True)),
                ('Date', models.CharField(max_length=200, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('completion_Status', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='source',
            field=models.CharField(choices=[('Install', 'Install'), ('Email Chain', 'Email Chain'), ('Fision Enterprise', 'Fision Enterprise'), ('Disco/Reco', 'Disco/Reco'), ('Project', 'Project'), ('Collections', 'Collections'), ('Miscellaneous', 'Miscellaneous'), ('Cog Call Back', 'Cog Call Back'), ('Inbound Tech Call', 'Inbound Tech Call'), ('Inbound Account Manager', 'Inbound Account Manager'), ('Inbound CS Agent', 'Inbound CS Agent'), ('Salisbury Gen tech support', 'Salisbury Gen tech support'), ('Fiber support', 'Fiber support'), ('change orders/disconnects/reconnects', 'change orders/disconnects/reconnects'), ('Trouble Ticket', 'Trouble Ticket'), ('Secure Plus', 'Secure Plus'), ('Collection Disconnect', 'Collection Disconnect')], max_length=500, null=True),
        ),
    ]
