# Generated by Django 3.1.2 on 2021-03-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210211_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='secure_Plus_Checker',
            field=models.CharField(choices=[('Eero Secure Plus Enabled', 'Eero Secure Plus Enabled'), ('Cannot activate Secure Plus', 'Cannot activate Secure Plus'), ('Eero Secure Plus Removed', 'Eero Secure Plus Removed'), ('Cannot deactivate Secure Plus', 'Cannot deactivate Secure Plus')], max_length=500, null=True),
        ),
    ]
