# Generated by Django 3.1.2 on 2021-03-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210315_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='secure_Plus_Checker',
            field=models.CharField(choices=[('Eero Secure Plus Enabled', 'Eero Secure Plus Enabled'), ('Cannot activate Secure Plus', 'Cannot activate Secure Plus'), ('Removed Eero Secure Plus Removed', 'Removed Eero Secure Plus Removed'), ('Failed to deactivate Secure Plus', 'Failed to deactivate Secure Plus')], max_length=500, null=True),
        ),
    ]
